### ISSUE TITLE
When is a task started?

### ISSUE THREAD

**Issue by JakeCoxon** [jeffijoe/mobx-task#1]
This lib looks very good

In the docs it says your code before..
```async fetchTodos () { ... } ```

fetchTodos isn't started until you explicitly call the function. 

Is a `@task` started as soon as it is created? Or upon accessing `store.fetchTodos`? It's not stated in the docs right now. It would be good to point out this difference from your-code-before. Thanks!

**Comment by jeffijoe** [comment]
That's a good point! The function is started when you call it - `task` just wraps it but sets the initial state to `pending`.

```
const func = task(() => 42)
// not running yet..

// start!
func()
```

**Comment by JakeCoxon** [comment]
Thanks for the reply! I think the `match` was throwing me off. does `func.match(...)` also start the task?

**Comment by jeffijoe** [comment]
Nope, that just does a pattern match on the state. :)

**Comment by JakeCoxon** [comment]
Awesome, this is going to be a big timesaver, thanks

**Comment by jeffijoe** [comment]
I've updated the readme to reflect when the task starts. Thanks for pointing this out, and let me know how it goes!
