### ISSUE TITLE
Track started/unstarted state of task

### ISSUE THREAD

**Issue by jacobdam** [jeffijoe/mobx-task#4]
Thanks for writing this library. It saves my time a lot. There is a small problem that task does not have a state to track if task started. The scenario that I am working on is: showing a form to allow user input information. The save button triggers to start the task. After saving, we show a message to user. So the problem is: we don't know if task started (to disable form and show spinner).

The temporary solution I am working on is add a state 'initial'. But this state is not official state.

```javascript
class TodoStore {
  @task({ state: 'initial' })
  submitTodo() {
    // send to server and update local array
  }
}

@observer
class AddTodo extends PureComponent {
  render() {
    const submitTodoTask = todoStore.submitTodo;

    if (submitTodoTask.state === 'initial') {
       return (<TodoForm state={this.state.formState} onChange={(formState) => {this.setState({ formState })}}>)
    }

    if (submitTodoTask.state === 'pending') {
      return (<Spinner>);
    }

    if (submitTodoTask.state === 'resolved') {
      return (<p>Added successfully!</p>);
    }
  }
};
```

Let me know what do you think?

**Comment by jeffijoe** [comment]
Glad you like it!

The 3 states are `pending`, `rejected` and `resolved`, which are more or less the official 3 states of a `Promise`, so I'm reluctant to add more states.

What you can do instead, is use `func.result` to determine is you have run the function before. By default it's `undefined`, so you can do something like this:

```js
class TodoStore {
  @task.resolved // sets state to resolved initially
  async submitTodo() {
    // send to server and update local array
    return true // now we have a result
  }
}

@observer
class AddTodo extends PureComponent {
  render() {
    const submitTodoTask = todoStore.submitTodo;

    if (submitTodoTask.state === 'pending') {
      return (<Spinner>);
    }

    if (submitTodoTask.state === 'resolved') {
      if (submitTodoTask.result) {
         return (<TodoForm state={this.state.formState} onChange={(formState) => {this.setState({ formState })}}>)
      }
      return (<p>Added successfully!</p>);
    }
  }
};
```

Also, as a sidenote, you can make your render code even more concise:

```js
@observer
class AddTodo extends PureComponent {
  render() {
    return todoStore.submitTodo.match({
      pending: () => <Spinner>,
      resolved: (result) => (
        result 
          ? (
            <TodoForm state={this.state.formState} onChange={(formState) => {this.setState({ formState })}}>
          )
          : <p>Added successfully!</p>
      )
    })
  }
};
```

Is this acceptable to you?

**Comment by jacobdam** [comment]
Thanks for your advice. Your solution should work for my use case. In my mind, a task is more like a function than a promise. As your point, task as promise is fit for scenarios that prepare data for components. But scenarios that wait user interaction then execute task, `mobx-task` does not work perfectly. I still have to write some duplicate code to manage the state if a task has been executed.

Again, thanks for writing this package.

**Comment by jeffijoe** [comment]
I use `mobx-task` for deferred interactions all the time using the approach above; what duplicate code are you referring to?

**Comment by corbanbrook** [comment]
What about in the case of a "Load More" button and a spinner. You don't want to show the loading spinner until after the button is clicked. But because there is the missing 'unstarted' state you would need to track that separately outside of the task state.

Because a task is not a promise but rather a promise creator, i think it makes sense to add the additional state.

**Comment by jeffijoe** [comment]
@corbanbrook yeah, I've done that using just `pending` and `resolved`.

```js
const loadMore = task.resolved(async () => {
  // ...
})

const View = () => (
  <div>
    {loadMore.pending
      ? <Spinner />
      : <button onClick={loadMore}>Load More</button>
    }
  </div>
)
```

This way, the task is initially `resolved` and the Load More button is displayed even when the task has not been run once yet.
