### ISSUE TITLE
Support to mobx v5

### ISSUE THREAD

**Issue by simmons8616** [jeffijoe/mobx-task#7]
When can you upgrade this library to support mobx v5?  thks!!!

**Comment by jeffijoe** [comment]
I will once I have upgraded my own code, I’m still on MobX v3 in some projects, however v1.0.0-alpha.0 supports v4.

**Comment by jeffijoe** [comment]
Give `v1.0.0-alpha.0` a try, I don't see why it wouldn't work with v5. 😄

**Comment by simmons8616** [comment]
@jeffijoe Thanks so much for providing such a great library.

**Comment by jeffijoe** [comment]
@simmons8616 I'm happy you find it useful!

**Comment by ricardovf** [comment]
Its working great on MobX 5.5. The lib is really useful, keep up the great work!

**Comment by jeffijoe** [comment]
Perfect, closing 😀
